<a href="https://colab.research.google.com/github/jacmantooth/groupproject/blob/main/groupproject4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Group Project Part 4

Gauss-Jordan Method is a method in solving linear equations in the form of 
$$
\left\{
\begin{align}
a_{1,1} x_1 +&\dots a_{1,n} x_n = y_1\\
&\vdots\\
a_{n,1}x_1+&\dots a_{n,n} x_n = y_n
\end{align}
\right.
$$


## Define functions for swapping rows, adding rows and multiplying by a constant

our first assigment was to define a function that can swap rows and multiple a row by a constant then add it to a row 

In [16]:
import numpy as np
import math

#example Matrix that i was messing around with
A = np.array([[5,2,3],[2,3,4]])


# First i def swapping of rows. first you pick the two rows you want to swap and it swaps it for you  
def swap(matrix,row,row2):
  matrix[[row, row2]] = matrix[[row2, row]]
  return matrix
#second i def adding rows. the first number is the row that stays the same then the second row is the one that gets row that you pick first to it. just a test function!! 

def addtest(matrix,row,row2):
  matrix[[row2]]=matrix[[row]]+matrix[[row2]]
  return matrix

# I will now def mult a row by a contants and adding it to a row. row2 is the one you want to change and row is the one that is get multiplied by the contant.
def add(matrix,row2,row,contant):
  newrow=matrix[row2,:]+contant*matrix[row,:]
  newMatrix = []
  for i in range(len(matrix)):
    if i != row2:
      newMatrix.append(matrix[i,:])
    else:
      newMatrix.append(newrow)
  return np.array(newMatrix)

# created to get leading one. row is the row you want to get the leading zero in and column being coloum of the number you want to have the leading zero. say i want a a leading zero in A[1,1] you would put 1 for row one and 1 for column 1.  
def leadone(matrix,row,column):
  newrow=matrix[row,:]/matrix[row,column]
  newMatrix = []
  for i in range(len(matrix)):
    if i != row:
      newMatrix.append(matrix[i,:])
    else:
      newMatrix.append(newrow)
  return np.array(newMatrix)

##Preforming Gauss-Jordan method on a system of at least three equations and three unknowns

the system of at least three equations and three unknows is 
$$
\begin{align}
-5x -4y + 5z &= 12\\
-10x + 4y -6z &= 52\\
20x + 4y + 2z &= -100\\
\end{align}
$$

In [94]:
B = np.array([[-5,-4,5,12],[-10,4,-6,52],[20,4,2,-100]])
B

array([[  -5,   -4,    5,   12],
       [ -10,    4,   -6,   52],
       [  20,    4,    2, -100]])

In [ ]:
we will be sloving the equation we picked using the fuction that we defined at the beganning

In [95]:
B=add(B,1,0,-2)
B=add(B,2,0,4)
B=add(B,2,1,1)
B=leadone(B,1,1)
B=add(B,0,1,4)
B=leadone(B,0,0)
B=leadone(B,2,2)
B=add(B,1,2,-B[1,2])
B=add(B,0,2,-B[0,2])
B

array([[ 1., -0.,  0., -4.],
       [ 0.,  1.,  0., -3.],
       [ 0.,  0.,  1., -4.]])

As you can the fuction that we defined at the beganning worked pretty well and it turns out our problem did have real number solutions 

##Creating an algorithm for solving a ystems of equations following the Gauss-Jordan elimination method and applying it to our system.

In [17]:
#my gaussJordan function.
def gaussJordan(matrix):
  newMatrix = matrix
  for pivot in range(len(matrix)):
    newMatrix = leadone(newMatrix,pivot,pivot)
    for column in range(0,pivot):
      newMatrix = add(newMatrix,column,pivot,-newMatrix[column,pivot])
    for column in range(pivot+1,len(matrix)):
        newMatrix = add(newMatrix,column,pivot,-newMatrix[column,pivot])
  return newMatrix

we will now be using guassJordan fuction to see if we are right

In [24]:
gaussJordan(B)

array([[ 1.,  0.,  0., -4.],
       [ 0.,  1.,  0., -3.],
       [ 0.,  0.,  1., -4.]])

looks like our gaussJordan function and us got the same answer!

#Report 