<a href="https://colab.research.google.com/github/jacmantooth/groupproject/blob/main/groupproject4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
import math

#example Matrix that i was messing around with
A = np.array([[5,2,3],[2,3,4]])
# First i def swapping of rows. pick the two rows you want to swap and it swaps with 
def swap(matrix,row,row2):
  matrix[[row, row2]] = matrix[[row2, row]]
  return matrix
#second i def adding rows. the first number is the row that stays the same then the second row is the one that gets row that you pick first to it. just a test!! 
def addt(matrix,row,row2):
  matrix[[row2]]=matrix[[row]]+matrix[[row2]]
  return matrix
#lastly i def mult a row by a contants and adding it to a row you want to change 
def add(matrix,row2,row,contant):
  newrow=matrix[row2,:]+contant*matrix[row,:]
  newMatrix = []
  for i in range(len(matrix)):
    if i != row2:
      newMatrix.append(matrix[i,:])
    else:
      newMatrix.append(newrow)
  return np.array(newMatrix)
# created to get leading one. row being the row you want to get the leading zero in and column being coloum of the number you want to have the leading zero
def leadone(matrix,row,column):
  newrow=matrix[row,:]/matrix[row,column]
  newMatrix = []
  for i in range(len(matrix)):
    if i != row:
      newMatrix.append(matrix[i,:])
    else:
      newMatrix.append(newrow)
  return np.array(newMatrix)

In [17]:
def gaussJordan(matrix):
  newMatrix = matrix
  for pivot in range(len(matrix)):
    newMatrix = leadone(newMatrix,pivot,pivot)
    for column in range(0,pivot):
      newMatrix = add(newMatrix,column,pivot,-newMatrix[column,pivot])
    for column in range(pivot+1,len(matrix)):
        newMatrix = add(newMatrix,column,pivot,-newMatrix[column,pivot])
  return newMatrix

Preform the Gauss-Jordan process using these functions on a system of at least three equations and three unknowns.

In [94]:
B = np.array([[-5,-4,5,12],[-10,4,-6,52],[20,4,2,-100]])
B

array([[  -5,   -4,    5,   12],
       [ -10,    4,   -6,   52],
       [  20,    4,    2, -100]])

In [95]:
B=add(B,1,0,-2)
B=add(B,2,0,4)
B=add(B,2,1,1)
B=leadone(B,1,1)
B=add(B,0,1,4)
B=leadone(B,0,0)
B=leadone(B,2,2)
B=add(B,1,2,-B[1,2])
B=add(B,0,2,-B[0,2])
B

array([[ 1., -0.,  0., -4.],
       [ 0.,  1.,  0., -3.],
       [ 0.,  0.,  1., -4.]])

In [24]:
gaussJordan(B)

array([[ 1.,  0.,  0., -4.],
       [ 0.,  1.,  0., -3.],
       [ 0.,  0.,  1., -4.]])